

/*
File: project_5_3.cpp
Created: 10/07/15 
Author: Martin Hernandez
email: 7607920511m.h@gmail.com
Description: Write a program that inputs a date (for example, July 4, 2008) and outputs
the day of the week that corresponds to that date.
*/

//Add libraries here
#include<iostream>
#include<cmath>
#include<string>

using namespace std;

//Declare functions here
void getinput(int&, int&, int&);
bool isLeapYear(int);
int getCenturyValue(int);
int getYearValue(int);
int getMonthValue(int, int);
void getdayoftheweek(int, int, int, int);

//Declare global variables here

int main() 
{       
    int monthinput; 
        int yearinput;
            int dateinput;

                getinput(monthinput, dateinput, yearinput);
                    getdayoftheweek(getMonthValue(monthinput, yearinput), dateinput, getYearValue(yearinput), getCenturyValue(yearinput));
                        cout << endl;
                            return 0;
                            } 

                            //Insert user defined funtions here
                            void getinput(int& monthinput, int& dateinput, int& yearinput)
                            {
                            /*  //string monthinput;
                                cout << "Enter the month please [1-12]: ";
                                    cin >> monthinput;
                                        cout  << "Enter the date please (dd format): ";
                                            cin >> dateinput;
                                                cout << "Please enter the year (yyyy format): ";
                                                    cin >> yearinput;
                                                        //getline(cin, rawinput);

                                                            //if (rawinput == "jan") {
                                                                //  monthinput = 1;
                                                                    //} 
                                                                    */  do {
                                                                            cout << "Enter the month please [1-12]: ";
                                                                                    cin >> monthinput;
                                                                                            }
                                                                                                while (monthinput > 12 || monthinput < 1); 
                                                                                                        
                                                                                                            do {    
                                                                                                                    cout << "Enter the date please (dd format): ";
                                                                                                                            cin >> dateinput;
                                                                                                                                    }
                                                                                                                                        while (dateinput > 31 || dateinput < 1);
                                                                                                                                            
                                                                                                                                                do {
                                                                                                                                                        cout << "Enter the year please (yyyy format): ";
                                                                                                                                                                cin >> yearinput;
                                                                                                                                                                        }
                                                                                                                                                                            while (yearinput > 9999 || yearinput < 1000);
                                                                                                                                                                            }

                                                                                                                                                                            bool isLeapYear(int year)
                                                                                                                                                                            {
                                                                                                                                                                                return (year / 400 == 0) || (((year / 4) && (!year / 100)));
                                                                                                                                                                                }


                                                                                                                                                                                int getCenturyValue(int year)
                                                                                                                                                                                {
                                                                                                                                                                                    return ((3-((year/100)%4))*2);
                                                                                                                                                                                    }

                                                                                                                                                                                    int getYearValue(int year)
                                                                                                                                                                                    {

                                                                                                                                                                                        return ((year % 100)/4) + (year %100);
                                                                                                                                                                                        }

                                                                                                                                                                                        int getMonthValue(int month, int year)
                                                                                                                                                                                        {

                                                                                                                                                                                            switch (month) 
                                                                                                                                                                                                {   
                                                                                                                                                                                                        case 1: //January
                                                                                                                                                                                                                    if(isLeapYear(year)) 
                                                                                                                                                                                                                                    { return 6; }
                                                                                                                                                                                                                                                else { return 0; }
                                                                                                                                                                                                                                                            break; 
                                                                                                                                                                                                                                                                    case 2: //February
                                                                                                                                                                                                                                                                                if(isLeapYear(year))
                                                                                                                                                                                                                                                                                                 { return 2; }
                                                                                                                                                                                                                                                                                                            else { return 3; }
                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                case 3: //March
                                                                                                                                                                                                                                                                                                                                            return 3;
                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                case 4: //April
                                                                                                                                                                                                                                                                                                                                                                            return 6;
                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                case 5: //May
                                                                                                                                                                                                                                                                                                                                                                                                            return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                case 6: //June
                                                                                                                                                                                                                                                                                                                                                                                                                                            return 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 7: //July
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 6;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 8: //August
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 9: //September
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 5;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 10: //October
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 11: //November
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 3;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 12: //December
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 5;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            throw "The world must have ended or we have changed our calender";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    void getdayoftheweek(int month, int date, int year, int cent)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int dayoftheweek;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int sumofdatetens;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int sumofdateones;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sumofdatetens = (date / 10);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sumofdateones = (date % 10);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cout << "Tens: " << sumofdatetens << endl << "Ones: " << sumofdateones << endl;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dayoftheweek = (sumofdatetens + sumofdateones + ((month+year+cent)%7));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    switch(dayoftheweek) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cout << "The weekday calculates to Monday.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 2: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cout << "The weekday calculates to Tuesday.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout << "The weekday calculates to Wednesday.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 4: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cout << "The weekday calculates to Thursday.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 5:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cout << "The weekday calculates to Friday.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 6:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cout << "The weekday calculates to Saterday.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout << "The weekday calculates to Sunday.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    throw "The world must have ended or we have changed our calendar";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
